services:
  mysql:
    image: mysql:8
    restart: always
    hostname: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_INITDB_ARGS=--lower-case-table-names=1
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql.cnf:/etc/mysql/my.cnf:ro
      - ./data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5